#!/usr/bin/python
# -*- coding: utf-8 -*-

#
# Copyright (c) 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


DOCUMENTATION = '''
---
module: ovirt_gluster_volumes
short_description: ovirt_gluster_volumes module to manage gluster-volumes in oVirt
author: "Ondra Machacek (@machacekondra)"
version_added: 2.0
description:
    - "This modules is used to manage oVirt gluster-volumes."
options:
    method:
        required: True
        description:
            - "Action to be run on gluster-volumes."
        choices:
            - add
            - list
            - get
            - get_profile_statistics
            - rebalance
            - remove
            - reset_all_options
            - reset_option
            - set_option
            - start
            - start_profile
            - stop
            - stop_profile
            - stop_rebalance
    auth:
        required: True
        description:
            - "Dictionary with values needed to create HTTP connection to oVirt:"
            - "** C(username)[I(required)] - The name of the user, something like `I(admin@internal)`."
            - "** C(password)[I(required)] - The password of the user."
            - "** C(url)[I(required)] - A string containing the base URL of the server, usually
            something like `I(https://server.example.com/ovirt-engine/api)`."
            - "** C(sso_token) - SSO token to be used instead of login with username/password."
            - "** C(insecure) - A boolean flag that indicates if the server TLS
            certificate and host name should be checked."
            - "** C(ca_file) - A PEM file containing the trusted CA certificates. The
            certificate presented by the server will be verified using these CA
            certificates. If `C(ca_file)` parameter is not set, system wide
            CA certificate store is used."
    service:
        required: false
        description:
            - "URL path of the service we want to work with, usually something like I(/vms/123/disks/456)."
    parameters:
        required: false
        description:
            - "Dictionary which specify additional parameters to be send with request."
            - " C(add) parameters:"
            - "** I(volume)[dict] - U(https://jhernand.fedorapeople.org/ovirt-api-explorer/#/types/volume)."
            - " C(list) parameters:"
            - "** I(max)[integer] - Sets the maximum number of volumes to return. If not specified all the volumes are returned."
            - "** I(search)[string] - A query string used to restrict the returned volumes."
            - "** I(case_sensitive)[boolean] - "
            - " C(rebalance) parameters:"
            - "** I(fix_layout)[boolean] - "
            - "** I(force)[boolean] - "
            - "** I(async)[boolean] - Indicates if the rebalance should be performed asynchronously."
            - " C(remove) parameters:"
            - "** I(async)[boolean] - Indicates if the remove should be performed asynchronously."
            - " C(reset_all_options) parameters:"
            - "** I(async)[boolean] - Indicates if the reset should be performed asynchronously."
            - " C(reset_option) parameters:"
            - "** I(force)[boolean] - "
            - "** I(option)[dict] - U(https://jhernand.fedorapeople.org/ovirt-api-explorer/#/types/option)."
            - "** I(async)[boolean] - Indicates if the reset should be performed asynchronously."
            - " C(set_option) parameters:"
            - "** I(option)[dict] - U(https://jhernand.fedorapeople.org/ovirt-api-explorer/#/types/option)."
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
            - " C(start) parameters:"
            - "** I(force)[boolean] - "
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
            - " C(start_profile) parameters:"
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
            - " C(stop) parameters:"
            - "** I(force)[boolean] - "
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
            - " C(stop_profile) parameters:"
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
            - " C(stop_rebalance) parameters:"
            - "** I(async)[boolean] - Indicates if the action should be performed asynchronously."
'''


RETURN = '''
'''


import sys
import json


def add(connection, path, **kwargs):
    request = Request(method='POST', path='%s/volumes' % path)
    request.body = json.dumps(kwargs.pop('volume'))
    response = connection.send(request)
    if response.code in [201, 202]:
        return {'changed': True, 'volume': response.body}
    return {'changed': False, 'error': response.body}


def get(connection, path, **kwargs):
    request = Request(method='GET', path='%s' % path, query=kwargs)
    response = connection.send(request)
    return {'changed': False, 'volume': response.body['volume']}


def get_profile_statistics(connection, path, **kwargs):
    request = Request(method='POST', path='%s/get_profile_statistics' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def list(connection, path, **kwargs):
    request = Request(method='GET', path='%s/volumes' % path, query=kwargs)
    response = connection.send(request)
    if 'volume' in response.body:
        return {'changed': False, 'volume': response.body['volume']}
    return {'changed': False, 'error': response.body}


def rebalance(connection, path, **kwargs):
    request = Request(method='POST', path='%s/rebalance' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def remove(connection, path, **kwargs):
    request = Request(method='DELETE', path='%s' % path, query=kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def reset_all_options(connection, path, **kwargs):
    request = Request(method='POST', path='%s/reset_all_options' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def reset_option(connection, path, **kwargs):
    request = Request(method='POST', path='%s/reset_option' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def set_option(connection, path, **kwargs):
    request = Request(method='POST', path='%s/set_option' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def start(connection, path, **kwargs):
    request = Request(method='POST', path='%s/start' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def start_profile(connection, path, **kwargs):
    request = Request(method='POST', path='%s/start_profile' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def stop(connection, path, **kwargs):
    request = Request(method='POST', path='%s/stop' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def stop_profile(connection, path, **kwargs):
    request = Request(method='POST', path='%s/stop_profile' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def stop_rebalance(connection, path, **kwargs):
    request = Request(method='POST', path='%s/stop_rebalance' % path)
    request.body = json.dumps(kwargs)
    response = connection.send(request)
    if response.code in [200]:
        return {'changed': True}
    return {'changed': False, 'error': response.body}


def main():
    module = AnsibleModule(
        argument_spec=dict(
            method=dict(required=True, choices=['add', 'list', 'get', 'get_profile_statistics', 'rebalance', 'remove', 'reset_all_options', 'reset_option', 'set_option', 'start', 'start_profile', 'stop', 'stop_profile', 'stop_rebalance']),
            auth=dict(required=True, type='dict'),
            service=dict(required=False, type='str', default=''),
            parameters=dict(required=False, type='dict', default=dict()),
        )
    )

    auth = module.params.pop('auth')
    connection = Connection(
        url=auth.get('url'),
        username=auth.get('username'),
        password=auth.get('password'),
        ca_file=auth.get('ca_file', None),
        insecure=auth.get('insecure', False),
        sso_token=auth.get('sso_token', None),
    )

    try:
        method = module.params.pop('method')
        ret = getattr(sys.modules[__name__], method)(connection, module.params['service'], **module.params.pop('parameters'))
        module.exit_json(**ret)
    except Error as e:
        module.fail_json(msg="Error: %s" % e)
    finally:
        if auth.get('sso_token', None) is None:
            connection.close()


from ansible.module_utils.basic import *
from ansible.module_utils.ovirt import *
if __name__ == "__main__":
    main()
