---
- hosts: localhost
  connection: local
  vars:
    auth:
      url: http://ondra.local/ovirt-engine/api
      username: admin@internal
      password: 1234567

  tasks:
  - name: Get datacenter dcx
    ov4_data_centers:
      auth: "{{ auth }}"
      method: list
      parameters:
        search: "name=dcx"
    register: dcx

  - name: Update dc
    ov4_data_centers:
      auth: "{{ auth }}"
      service: "{{ dcx.data_center[0].href }}"
      method: update
      parameters:
        data_center:
          name: dcy
    when: dcx.error is undefined
